<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>lib.pwss.cryptographic_algorithm</groupId>
    <artifactId>cryptographic_algorithm</artifactId>
    <version>1.1</version>
    <description>A set of classes designed to simplify the implementation of cryptographic algorithms, focusing on ensuring file
        integrity through hash functions.</description>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub pwssOrg Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/pwssOrg/literate-octo-guacamole</url>
        </repository>
    </distributionManagement>


    <developers>
    <developer>
        <name>Peter Westin</name>
        <id>Peter</id>
        <email>snow_900@outlook.com</email>
        <roles>
            <role>Coa supporter</role>
        </roles>
        <timezone>Central European Time</timezone>
    </developer>
    </developers>

    <licenses>
        <license>
            <name>Proprietary License</name>
            <url>https://github.com/pwssOrg/literate-octo-guacamole/blob/main/LICENSE.md</url>
            <distribution>repo</distribution>
            <comments>
                This software and its source code are proprietary to Peter Westin (pwgit-create) and Stefan Smudja
                (lilstiffy). All rights
                reserved. This project may not be copied or used for commercial purposes without the explicit permission
                of the
                copyright holders.
            </comments>
        </license>
    </licenses>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.81</version>
        </dependency>
    </dependencies>

</project>